//
// Copyright 2023-Present (c) Raja Lehtihet & Wael El Oraiby
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//

use microui_redux::prelude::*;
use microui_redux::{AtlasSource, SourceFormat};

pub fn external_atlas_source(pixels: &[u8]) -> AtlasSource<'_> {
    AtlasSource {
width: 512, height: 256,
icons: &[
("white", Rect { x: 1, y: 1, width: 24, height: 24 }),("close", Rect { x: 26, y: 1, width: 24, height: 24 }),("expand", Rect { x: 51, y: 1, width: 24, height: 24 }),("collapse", Rect { x: 76, y: 1, width: 24, height: 24 }),("check", Rect { x: 101, y: 1, width: 24, height: 24 }),("expand_down", Rect { x: 126, y: 1, width: 24, height: 24 }),("open_folder", Rect { x: 151, y: 1, width: 16, height: 16 }),("closed_folder", Rect { x: 168, y: 1, width: 16, height: 16 }),("file", Rect { x: 185, y: 1, width: 16, height: 16 }),],
fonts: &[
("body", FontEntry { line_size: 16, baseline: 13, font_size: 12, entries: &[
('P', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 382, y: 9, width: 6, height: 9 }, }),
('2', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 310, y: 1, width: 7, height: 9 }, }),
('>', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 398, y: 1, width: 7, height: 7 }, }),
('K', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 495, y: 1, width: 7, height: 9 }, }),
('L', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 503, y: 1, width: 5, height: 9 }, }),
(';', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 378, y: 1, width: 3, height: 9 }, }),
('G', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 470, y: 1, width: 8, height: 10 }, }),
('_', CharEntry { offset: Vec2i { x: -1, y:-2 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 450, y: 11, width: 7, height: 1 }, }),
('1', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 305, y: 1, width: 4, height: 9 }, }),
('}', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 169, y: 18, width: 5, height: 11 }, }),
('5', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 334, y: 1, width: 7, height: 10 }, }),
('<', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 382, y: 1, width: 7, height: 7 }, }),
('@', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 412, y: 1, width: 11, height: 11 }, }),
('H', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 479, y: 1, width: 7, height: 9 }, }),
('Z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 503, y: 11, width: 7, height: 9 }, }),
(':', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 374, y: 1, width: 3, height: 8 }, }),
('k', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 363, y: 12, width: 6, height: 10 }, }),
('I', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 487, y: 1, width: 2, height: 9 }, }),
('V', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 479, y: 11, width: 8, height: 9 }, }),
('D', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 450, y: 1, width: 7, height: 9 }, }),
('l', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 249, y: 6, width: 2, height: 10 }, }),
('s', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 417, y: 13, width: 6, height: 8 }, }),
('(', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 252, y: 1, width: 4, height: 11 }, }),
('X', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 350, y: 11, width: 7, height: 9 }, }),
('t', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 488, y: 14, width: 5, height: 9 }, }),
('N', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 390, y: 6, width: 7, height: 9 }, }),
('E', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 458, y: 1, width: 5, height: 9 }, }),
('W', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 305, y: 11, width: 11, height: 9 }, }),
('6', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 342, y: 1, width: 7, height: 10 }, }),
('i', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 202, y: 12, width: 3, height: 9 }, }),
('h', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 342, y: 12, width: 6, height: 10 }, }),
('r', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 412, y: 13, width: 4, height: 7 }, }),
('3', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 318, y: 1, width: 7, height: 10 }, }),
(' ', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 0, y: 0, width: 0, height: 0 }, }),
('O', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 262, y: 9, width: 9, height: 10 }, }),
('y', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 430, y: 18, width: 7, height: 10 }, }),
('g', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 334, y: 12, width: 7, height: 10 }, }),
('Y', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 495, y: 11, width: 7, height: 9 }, }),
('B', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 433, y: 1, width: 7, height: 9 }, }),
('{', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 246, y: 17, width: 5, height: 11 }, }),
('~', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 175, y: 18, width: 7, height: 2 }, }),
('b', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 296, y: 12, width: 6, height: 11 }, }),
('e', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 438, y: 12, width: 7, height: 8 }, }),
('+', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 270, y: 1, width: 7, height: 7 }, }),
('&', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 239, y: 1, width: 9, height: 10 }, }),
('8', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 358, y: 1, width: 7, height: 10 }, }),
('-', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 282, y: 1, width: 4, height: 2 }, }),
('!', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 202, y: 1, width: 3, height: 10 }, }),
('\'', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 249, y: 1, width: 2, height: 4 }, }),
('^', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 430, y: 11, width: 7, height: 6 }, }),
('f', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 406, y: 12, width: 5, height: 10 }, }),
('|', CharEntry { offset: Vec2i { x: 2, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 370, y: 12, width: 2, height: 13 }, }),
('c', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 317, y: 12, width: 6, height: 8 }, }),
('.', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 287, y: 1, width: 3, height: 3 }, }),
('x', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 389, y: 16, width: 7, height: 7 }, }),
('o', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 446, y: 13, width: 7, height: 8 }, }),
('0', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 297, y: 1, width: 7, height: 10 }, }),
('4', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 326, y: 1, width: 7, height: 9 }, }),
('U', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 326, y: 11, width: 7, height: 10 }, }),
(')', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 257, y: 1, width: 4, height: 11 }, }),
('/', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 291, y: 1, width: 5, height: 9 }, }),
('p', CharEntry { offset: Vec2i { x: 1, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 220, y: 13, width: 6, height: 10 }, }),
('w', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 151, y: 18, width: 10, height: 7 }, }),
('9', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 366, y: 1, width: 7, height: 10 }, }),
(']', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 216, y: 11, width: 3, height: 11 }, }),
('q', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 252, y: 13, width: 7, height: 10 }, }),
('Q', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 206, y: 11, width: 9, height: 12 }, }),
('=', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 390, y: 1, width: 7, height: 4 }, }),
('R', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 398, y: 9, width: 7, height: 9 }, }),
('?', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 406, y: 1, width: 5, height: 10 }, }),
('F', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 464, y: 1, width: 5, height: 9 }, }),
('T', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 374, y: 11, width: 7, height: 9 }, }),
('\\', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 424, y: 11, width: 5, height: 9 }, }),
('*', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 262, y: 1, width: 7, height: 7 }, }),
('d', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 469, y: 12, width: 7, height: 11 }, }),
('A', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 424, y: 1, width: 8, height: 9 }, }),
('j', CharEntry { offset: Vec2i { x: -1, y:-3 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 358, y: 12, width: 4, height: 12 }, }),
('"', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 206, y: 1, width: 4, height: 4 }, }),
('n', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 239, y: 12, width: 6, height: 7 }, }),
('M', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 278, y: 6, width: 9, height: 9 }, }),
('`', CharEntry { offset: Vec2i { x: 0, y:7 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 458, y: 11, width: 3, height: 3 }, }),
('C', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 441, y: 1, width: 8, height: 10 }, }),
('[', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 272, y: 9, width: 4, height: 11 }, }),
('a', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 462, y: 11, width: 6, height: 8 }, }),
('m', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 228, y: 12, width: 10, height: 7 }, }),
('J', CharEntry { offset: Vec2i { x: -1, y:-3 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 490, y: 1, width: 4, height: 12 }, }),
('S', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 288, y: 11, width: 7, height: 10 }, }),
(',', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 278, y: 1, width: 3, height: 4 }, }),
('u', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 454, y: 15, width: 7, height: 8 }, }),
('v', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 277, y: 16, width: 6, height: 7 }, }),
('%', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 228, y: 1, width: 10, height: 10 }, }),
('7', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 350, y: 1, width: 7, height: 9 }, }),
('z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 162, y: 18, width: 6, height: 7 }, }),
('$', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 220, y: 1, width: 7, height: 11 }, }),
('#', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 211, y: 1, width: 8, height: 9 }, }),
]
 }),
("small", FontEntry { line_size: 14, baseline: 11, font_size: 10, entries: &[
('s', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 396, y: 29, width: 5, height: 7 }, }),
('w', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 61, y: 29, width: 8, height: 6 }, }),
('.', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 386, y: 19, width: 2, height: 3 }, }),
('}', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 434, y: 30, width: 4, height: 10 }, }),
('m', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 135, y: 26, width: 9, height: 6 }, }),
('A', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 404, y: 23, width: 7, height: 8 }, }),
('~', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 317, y: 30, width: 6, height: 3 }, }),
('[', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 488, y: 24, width: 4, height: 10 }, }),
('u', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 243, y: 29, width: 6, height: 7 }, }),
('2', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 269, y: 21, width: 6, height: 8 }, }),
('z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 493, y: 30, width: 5, height: 6 }, }),
('Y', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 412, y: 26, width: 6, height: 8 }, }),
('`', CharEntry { offset: Vec2i { x: 0, y:6 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 68, y: 26, width: 3, height: 2 }, }),
('f', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 105, y: 26, width: 4, height: 8 }, }),
('<', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 324, y: 22, width: 6, height: 6 }, }),
('O', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 1, y: 26, width: 8, height: 9 }, }),
('0', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 303, y: 21, width: 6, height: 9 }, }),
('4', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 438, y: 21, width: 6, height: 8 }, }),
('6', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 310, y: 21, width: 6, height: 9 }, }),
('U', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 19, y: 26, width: 7, height: 9 }, }),
('@', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 331, y: 23, width: 9, height: 9 }, }),
('_', CharEntry { offset: Vec2i { x: -1, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 61, y: 26, width: 6, height: 2 }, }),
('n', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 145, y: 26, width: 6, height: 6 }, }),
('{', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 381, y: 30, width: 4, height: 10 }, }),
('+', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 349, y: 21, width: 6, height: 5 }, }),
('a', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 72, y: 26, width: 5, height: 7 }, }),
('(', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 382, y: 19, width: 3, height: 10 }, }),
('T', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 356, y: 25, width: 6, height: 8 }, }),
('B', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 196, y: 23, width: 6, height: 8 }, }),
('/', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 494, y: 21, width: 4, height: 8 }, }),
('1', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 477, y: 21, width: 4, height: 8 }, }),
('^', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 54, y: 26, width: 6, height: 6 }, }),
('l', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 284, y: 26, width: 2, height: 8 }, }),
('3', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 175, y: 21, width: 6, height: 9 }, }),
('v', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 324, y: 29, width: 5, height: 6 }, }),
(':', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 243, y: 20, width: 2, height: 7 }, }),
('k', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 128, y: 26, width: 6, height: 8 }, }),
('9', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 445, y: 22, width: 6, height: 9 }, }),
('y', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 476, y: 30, width: 6, height: 9 }, }),
('N', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 216, y: 24, width: 7, height: 8 }, }),
('5', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 499, y: 21, width: 6, height: 9 }, }),
('E', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 482, y: 21, width: 5, height: 8 }, }),
('L', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 203, y: 24, width: 5, height: 8 }, }),
(')', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 462, y: 20, width: 3, height: 10 }, }),
('J', CharEntry { offset: Vec2i { x: -1, y:-2 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 377, y: 21, width: 3, height: 10 }, }),
('x', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 419, y: 29, width: 6, height: 6 }, }),
('H', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 294, y: 24, width: 7, height: 8 }, }),
(',', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 199, y: 18, width: 2, height: 4 }, }),
('-', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 373, y: 21, width: 3, height: 2 }, }),
('h', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 117, y: 26, width: 6, height: 8 }, }),
('X', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 236, y: 26, width: 6, height: 8 }, }),
('!', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 284, y: 16, width: 2, height: 9 }, }),
('?', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 506, y: 21, width: 5, height: 9 }, }),
('Z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 38, y: 26, width: 6, height: 8 }, }),
('o', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 152, y: 26, width: 6, height: 7 }, }),
(' ', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 0, y: 0, width: 0, height: 0 }, }),
('$', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 397, y: 19, width: 6, height: 9 }, }),
('*', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 236, y: 20, width: 6, height: 5 }, }),
('G', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 276, y: 24, width: 7, height: 9 }, }),
('Q', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 10, y: 26, width: 8, height: 10 }, }),
('e', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 98, y: 26, width: 6, height: 7 }, }),
('p', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 159, y: 26, width: 6, height: 9 }, }),
('>', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 419, y: 22, width: 6, height: 6 }, }),
('K', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 452, y: 24, width: 7, height: 8 }, }),
('|', CharEntry { offset: Vec2i { x: 2, y:-3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 166, y: 26, width: 2, height: 11 }, }),
('M', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 386, y: 24, width: 9, height: 8 }, }),
('I', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 426, y: 21, width: 2, height: 8 }, }),
('\\', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 45, y: 26, width: 4, height: 8 }, }),
('V', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 370, y: 26, width: 6, height: 8 }, }),
('&', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 260, y: 20, width: 8, height: 9 }, }),
('"', CharEntry { offset: Vec2i { x: 0, y:4 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 183, y: 18, width: 4, height: 4 }, }),
('7', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 317, y: 21, width: 6, height: 8 }, }),
('8', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 287, y: 22, width: 6, height: 9 }, }),
('D', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 341, y: 23, width: 7, height: 8 }, }),
('F', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 182, y: 23, width: 5, height: 8 }, }),
('R', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 252, y: 24, width: 7, height: 8 }, }),
('d', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 91, y: 26, width: 6, height: 9 }, }),
('g', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 110, y: 26, width: 6, height: 9 }, }),
('i', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 224, y: 24, width: 2, height: 8 }, }),
('\'', CharEntry { offset: Vec2i { x: 0, y:4 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 196, y: 18, width: 2, height: 4 }, }),
('=', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 412, y: 22, width: 6, height: 3 }, }),
('r', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 188, y: 27, width: 4, height: 6 }, }),
('t', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 429, y: 29, width: 4, height: 8 }, }),
(';', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 466, y: 20, width: 2, height: 8 }, }),
('b', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 78, y: 26, width: 6, height: 9 }, }),
('W', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 27, y: 26, width: 10, height: 8 }, }),
('#', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 188, y: 18, width: 7, height: 8 }, }),
('C', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 363, y: 23, width: 6, height: 9 }, }),
(']', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 50, y: 26, width: 3, height: 10 }, }),
('S', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 469, y: 24, width: 6, height: 9 }, }),
('%', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 227, y: 20, width: 8, height: 9 }, }),
('P', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 209, y: 24, width: 6, height: 8 }, }),
('c', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 85, y: 26, width: 5, height: 7 }, }),
('j', CharEntry { offset: Vec2i { x: -1, y:-3 }, advance: Vec2i { x:2, y: 0 }, rect: Recti {x: 124, y: 26, width: 3, height: 11 }, }),
('q', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 349, y: 27, width: 6, height: 9 }, }),
]
 }),
("title", FontEntry { line_size: 16, baseline: 13, font_size: 12, entries: &[
('v', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 456, y: 43, width: 7, height: 7 }, }),
('D', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 368, y: 35, width: 8, height: 9 }, }),
('8', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 135, y: 33, width: 7, height: 10 }, }),
('b', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 439, y: 40, width: 8, height: 11 }, }),
('0', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 341, y: 32, width: 7, height: 10 }, }),
('V', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 236, y: 37, width: 8, height: 9 }, }),
('+', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 443, y: 32, width: 7, height: 7 }, }),
('3', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 330, y: 33, width: 7, height: 10 }, }),
('-', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 175, y: 31, width: 4, height: 2 }, }),
('1', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 287, y: 32, width: 5, height: 9 }, }),
('J', CharEntry { offset: Vec2i { x: -1, y:-3 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 188, y: 34, width: 4, height: 12 }, }),
('d', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 476, y: 41, width: 7, height: 11 }, }),
('T', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 61, y: 36, width: 7, height: 9 }, }),
('c', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 349, y: 37, width: 6, height: 8 }, }),
('m', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 497, y: 42, width: 11, height: 7 }, }),
('<', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 207, y: 33, width: 7, height: 7 }, }),
('p', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 385, y: 43, width: 8, height: 10 }, }),
('5', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 250, y: 33, width: 7, height: 10 }, }),
('q', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 291, y: 43, width: 7, height: 10 }, }),
('y', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 83, y: 44, width: 7, height: 10 }, }),
('j', CharEntry { offset: Vec2i { x: -1, y:-3 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 245, y: 37, width: 4, height: 13 }, }),
('z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 328, y: 44, width: 6, height: 7 }, }),
('|', CharEntry { offset: Vec2i { x: 2, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 509, y: 31, width: 2, height: 13 }, }),
('Z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 46, y: 37, width: 7, height: 9 }, }),
('[', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 323, y: 36, width: 4, height: 11 }, }),
('%', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 302, y: 31, width: 11, height: 10 }, }),
('/', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 193, y: 32, width: 5, height: 9 }, }),
('$', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 260, y: 30, width: 7, height: 11 }, }),
('>', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 151, y: 34, width: 7, height: 7 }, }),
('B', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 70, y: 34, width: 7, height: 9 }, }),
('Y', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 215, y: 38, width: 8, height: 9 }, }),
('^', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 224, y: 40, width: 7, height: 6 }, }),
('e', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 207, y: 41, width: 7, height: 8 }, }),
('f', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 91, y: 38, width: 6, height: 10 }, }),
('4', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 451, y: 33, width: 7, height: 9 }, }),
('k', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 258, y: 42, width: 8, height: 10 }, }),
('M', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 35, y: 35, width: 10, height: 9 }, }),
('C', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 314, y: 34, width: 8, height: 10 }, }),
('s', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 338, y: 43, width: 6, height: 8 }, }),
('}', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 98, y: 44, width: 5, height: 11 }, }),
('E', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 98, y: 34, width: 6, height: 9 }, }),
('`', CharEntry { offset: Vec2i { x: 0, y:7 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 419, y: 36, width: 4, height: 3 }, }),
('2', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 293, y: 33, width: 7, height: 9 }, }),
('R', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 19, y: 36, width: 7, height: 9 }, }),
('_', CharEntry { offset: Vec2i { x: -1, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 91, y: 36, width: 6, height: 1 }, }),
('g', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 283, y: 42, width: 7, height: 10 }, }),
('{', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 54, y: 44, width: 5, height: 11 }, }),
('h', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 301, y: 42, width: 7, height: 10 }, }),
('w', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 267, y: 44, width: 11, height: 7 }, }),
('G', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 410, y: 35, width: 8, height: 10 }, }),
('=', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 215, y: 33, width: 7, height: 4 }, }),
('t', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 193, y: 42, width: 5, height: 9 }, }),
('(', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 268, y: 30, width: 4, height: 11 }, }),
('?', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 54, y: 33, width: 6, height: 10 }, }),
('Q', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 487, y: 37, width: 9, height: 12 }, }),
('7', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 386, y: 33, width: 7, height: 9 }, }),
('H', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 169, y: 35, width: 8, height: 9 }, }),
(';', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 377, y: 32, width: 3, height: 9 }, }),
(':', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 184, y: 32, width: 3, height: 8 }, }),
('\\', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 178, y: 36, width: 5, height: 9 }, }),
(']', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 78, y: 36, width: 4, height: 11 }, }),
('a', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 424, y: 40, width: 7, height: 8 }, }),
('o', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 151, y: 42, width: 7, height: 8 }, }),
('6', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 199, y: 33, width: 7, height: 10 }, }),
('"', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 169, y: 30, width: 5, height: 4 }, }),
('F', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 85, y: 34, width: 5, height: 9 }, }),
('I', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 426, y: 30, width: 2, height: 9 }, }),
('L', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 469, y: 34, width: 6, height: 9 }, }),
('X', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 159, y: 38, width: 9, height: 9 }, }),
('r', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 432, y: 41, width: 6, height: 7 }, }),
('&', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 499, y: 31, width: 9, height: 10 }, }),
(',', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 465, y: 31, width: 3, height: 4 }, }),
('9', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 143, y: 33, width: 7, height: 10 }, }),
('N', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 105, y: 36, width: 8, height: 9 }, }),
('O', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 114, y: 36, width: 9, height: 10 }, }),
('P', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 128, y: 35, width: 6, height: 9 }, }),
('l', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 124, y: 38, width: 3, height: 10 }, }),
('W', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 394, y: 40, width: 12, height: 9 }, }),
('@', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 356, y: 34, width: 11, height: 11 }, }),
('u', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 448, y: 43, width: 7, height: 8 }, }),
(' ', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 0, y: 0, width: 0, height: 0 }, }),
('x', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 69, y: 44, width: 7, height: 7 }, }),
('*', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 402, y: 32, width: 7, height: 7 }, }),
('A', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 273, y: 34, width: 9, height: 9 }, }),
('.', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 180, y: 32, width: 3, height: 3 }, }),
('K', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 27, y: 35, width: 7, height: 9 }, }),
('S', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 1, y: 36, width: 7, height: 10 }, }),
('#', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 227, y: 30, width: 8, height: 9 }, }),
(')', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 460, y: 31, width: 4, height: 11 }, }),
('i', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 465, y: 36, width: 3, height: 10 }, }),
('!', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 483, y: 30, width: 3, height: 10 }, }),
('U', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 9, y: 37, width: 8, height: 10 }, }),
('\'', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 439, y: 30, width: 3, height: 4 }, }),
('n', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 377, y: 42, width: 7, height: 7 }, }),
('~', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 199, y: 44, width: 7, height: 3 }, }),
]
 }),
("heading", FontEntry { line_size: 25, baseline: 19, font_size: 18, entries: &[
('E', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 319, y: 48, width: 8, height: 13 }, }),
('f', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 126, y: 62, width: 7, height: 14 }, }),
('.', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 184, y: 41, width: 3, height: 4 }, }),
('l', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 64, y: 60, width: 3, height: 14 }, }),
('>', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 373, y: 50, width: 10, height: 9 }, }),
('F', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 335, y: 52, width: 8, height: 13 }, }),
('j', CharEntry { offset: Vec2i { x: -1, y:-5 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 329, y: 57, width: 5, height: 19 }, }),
('x', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 445, y: 66, width: 10, height: 10 }, }),
('}', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 256, y: 67, width: 7, height: 16 }, }),
('?', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 236, y: 47, width: 8, height: 15 }, }),
('c', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 407, y: 62, width: 8, height: 11 }, }),
('h', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 416, y: 63, width: 9, height: 14 }, }),
('^', CharEntry { offset: Vec2i { x: 0, y:4 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 225, y: 61, width: 10, height: 9 }, }),
(':', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 279, y: 44, width: 3, height: 11 }, }),
('2', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 111, y: 47, width: 10, height: 14 }, }),
('d', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 309, y: 62, width: 9, height: 15 }, }),
('!', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 232, y: 40, width: 3, height: 14 }, }),
('-', CharEntry { offset: Vec2i { x: 0, y:4 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 18, y: 46, width: 6, height: 2 }, }),
('(', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 250, y: 44, width: 5, height: 16 }, }),
('P', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 256, y: 53, width: 9, height: 13 }, }),
('V', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 379, y: 60, width: 11, height: 13 }, }),
('3', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 42, y: 47, width: 10, height: 15 }, }),
('o', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 246, y: 64, width: 9, height: 11 }, }),
('/', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 60, y: 46, width: 7, height: 13 }, }),
(';', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 225, y: 47, width: 4, height: 13 }, }),
('q', CharEntry { offset: Vec2i { x: 0, y:-5 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 11, y: 65, width: 10, height: 15 }, }),
('g', CharEntry { offset: Vec2i { x: 0, y:-5 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 40, y: 63, width: 10, height: 15 }, }),
('n', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 236, y: 64, width: 9, height: 10 }, }),
('{', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 471, y: 67, width: 7, height: 16 }, }),
('a', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 110, y: 62, width: 9, height: 11 }, }),
('e', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 319, y: 62, width: 9, height: 11 }, }),
('J', CharEntry { offset: Vec2i { x: -2, y:-4 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 91, y: 49, width: 6, height: 17 }, }),
('v', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 68, y: 66, width: 9, height: 10 }, }),
('H', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:13, y: 0 }, rect: Recti {x: 445, y: 52, width: 11, height: 13 }, }),
('i', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 279, y: 56, width: 3, height: 14 }, }),
('Z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 484, y: 60, width: 10, height: 13 }, }),
('S', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 80, y: 55, width: 10, height: 15 }, }),
('`', CharEntry { offset: Vec2i { x: 0, y:10 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 328, y: 52, width: 5, height: 4 }, }),
('*', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 345, y: 46, width: 10, height: 9 }, }),
('L', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 475, y: 53, width: 8, height: 13 }, }),
('M', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:16, y: 0 }, rect: Recti {x: 283, y: 54, width: 14, height: 13 }, }),
('p', CharEntry { offset: Vec2i { x: 1, y:-5 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 495, y: 64, width: 10, height: 15 }, }),
('N', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:13, y: 0 }, rect: Recti {x: 344, y: 56, width: 11, height: 13 }, }),
('y', CharEntry { offset: Vec2i { x: 0, y:-5 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 147, y: 67, width: 10, height: 15 }, }),
('D', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:13, y: 0 }, rect: Recti {x: 68, y: 52, width: 11, height: 13 }, }),
('&', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:13, y: 0 }, rect: Recti {x: 407, y: 46, width: 14, height: 15 }, }),
('"', CharEntry { offset: Vec2i { x: 1, y:8 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 469, y: 44, width: 5, height: 5 }, }),
('%', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:14, y: 0 }, rect: Recti {x: 27, y: 45, width: 14, height: 15 }, }),
('6', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 215, y: 48, width: 9, height: 15 }, }),
('U', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:13, y: 0 }, rect: Recti {x: 367, y: 60, width: 11, height: 14 }, }),
('W', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:16, y: 0 }, rect: Recti {x: 22, y: 61, width: 17, height: 13 }, }),
(',', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 368, y: 45, width: 4, height: 6 }, }),
('4', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 180, y: 47, width: 10, height: 13 }, }),
('Q', CharEntry { offset: Vec2i { x: 1, y:-4 }, advance: Vec2i { x:14, y: 0 }, rect: Recti {x: 134, y: 58, width: 12, height: 18 }, }),
('0', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 356, y: 46, width: 10, height: 15 }, }),
('k', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 1, y: 63, width: 9, height: 14 }, }),
(' ', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:4, y: 0 }, rect: Recti {x: 0, y: 0, width: 0, height: 0 }, }),
('r', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 215, y: 64, width: 7, height: 10 }, }),
('t', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 463, y: 66, width: 7, height: 13 }, }),
('+', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 169, y: 46, width: 10, height: 9 }, }),
('~', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 426, y: 68, width: 10, height: 3 }, }),
('\'', CharEntry { offset: Vec2i { x: 1, y:8 }, advance: Vec2i { x:3, y: 0 }, rect: Recti {x: 484, y: 41, width: 2, height: 5 }, }),
('C', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 148, y: 51, width: 10, height: 15 }, }),
('#', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 135, y: 44, width: 12, height: 13 }, }),
('1', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 104, y: 46, width: 6, height: 13 }, }),
('@', CharEntry { offset: Vec2i { x: 1, y:-2 }, advance: Vec2i { x:16, y: 0 }, rect: Recti {x: 199, y: 50, width: 15, height: 15 }, }),
('$', CharEntry { offset: Vec2i { x: 1, y:-2 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 309, y: 45, width: 9, height: 16 }, }),
('B', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 495, y: 50, width: 10, height: 13 }, }),
('A', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 394, y: 50, width: 12, height: 13 }, }),
('I', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 122, y: 49, width: 3, height: 13 }, }),
('K', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 267, y: 52, width: 11, height: 13 }, }),
('8', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 11, y: 49, width: 10, height: 15 }, }),
('\\', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:6, y: 0 }, rect: Recti {x: 191, y: 52, width: 7, height: 13 }, }),
('s', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 266, y: 66, width: 8, height: 11 }, }),
('X', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 98, y: 60, width: 11, height: 13 }, }),
('_', CharEntry { offset: Vec2i { x: -1, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 245, y: 61, width: 9, height: 2 }, }),
(']', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 457, y: 51, width: 5, height: 16 }, }),
('[', CharEntry { offset: Vec2i { x: 1, y:-3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 506, y: 50, width: 5, height: 16 }, }),
('5', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 1, y: 48, width: 9, height: 14 }, }),
('w', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:13, y: 0 }, rect: Recti {x: 194, y: 66, width: 14, height: 10 }, }),
('O', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:14, y: 0 }, rect: Recti {x: 159, y: 56, width: 12, height: 15 }, }),
('<', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 484, y: 50, width: 10, height: 9 }, }),
('m', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:16, y: 0 }, rect: Recti {x: 391, y: 64, width: 15, height: 10 }, }),
('u', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 184, y: 66, width: 9, height: 11 }, }),
('R', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 298, y: 54, width: 10, height: 13 }, }),
(')', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:5, y: 0 }, rect: Recti {x: 128, y: 45, width: 5, height: 16 }, }),
('Y', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 172, y: 61, width: 11, height: 13 }, }),
('b', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:11, y: 0 }, rect: Recti {x: 356, y: 62, width: 10, height: 15 }, }),
('|', CharEntry { offset: Vec2i { x: 4, y:-5 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 120, y: 63, width: 2, height: 19 }, }),
('T', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:9, y: 0 }, rect: Recti {x: 53, y: 60, width: 10, height: 13 }, }),
('7', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 422, y: 49, width: 10, height: 13 }, }),
('G', CharEntry { offset: Vec2i { x: 1, y:-1 }, advance: Vec2i { x:13, y: 0 }, rect: Recti {x: 433, y: 52, width: 11, height: 15 }, }),
('z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:8, y: 0 }, rect: Recti {x: 335, y: 66, width: 8, height: 10 }, }),
('9', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 464, y: 50, width: 10, height: 15 }, }),
('=', CharEntry { offset: Vec2i { x: 1, y:3 }, advance: Vec2i { x:10, y: 0 }, rect: Recti {x: 159, y: 48, width: 9, height: 6 }, }),
]
 }),
("mono", FontEntry { line_size: 14, baseline: 11, font_size: 14, entries: &[
('k', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 291, y: 81, width: 7, height: 8 }, }),
('M', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 441, y: 77, width: 7, height: 8 }, }),
('n', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 83, y: 82, width: 7, height: 7 }, }),
('-', CharEntry { offset: Vec2i { x: 0, y:3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 275, y: 71, width: 7, height: 2 }, }),
('j', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 360, y: 78, width: 6, height: 12 }, }),
('x', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 479, y: 83, width: 7, height: 7 }, }),
('+', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 223, y: 71, width: 7, height: 6 }, }),
('=', CharEntry { offset: Vec2i { x: 0, y:2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 105, y: 74, width: 7, height: 4 }, }),
('W', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 75, y: 78, width: 7, height: 8 }, }),
('%', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 299, y: 68, width: 7, height: 10 }, }),
('D', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 395, y: 75, width: 7, height: 8 }, }),
('?', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 59, y: 75, width: 7, height: 8 }, }),
('$', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 291, y: 68, width: 7, height: 12 }, }),
('6', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 275, y: 74, width: 7, height: 8 }, }),
('1', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 426, y: 72, width: 6, height: 8 }, }),
('i', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 225, y: 81, width: 7, height: 9 }, }),
(';', CharEntry { offset: Vec2i { x: 2, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 231, y: 71, width: 4, height: 9 }, }),
('*', CharEntry { offset: Vec2i { x: 0, y:1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 78, y: 71, width: 7, height: 6 }, }),
(' ', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 0, y: 0, width: 0, height: 0 }, }),
('r', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 403, y: 83, width: 7, height: 7 }, }),
('4', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 51, y: 74, width: 7, height: 8 }, }),
('<', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 379, y: 74, width: 7, height: 8 }, }),
('@', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 166, y: 75, width: 7, height: 8 }, }),
(')', CharEntry { offset: Vec2i { x: 1, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 91, y: 67, width: 5, height: 10 }, }),
('(', CharEntry { offset: Vec2i { x: 1, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 506, y: 67, width: 5, height: 10 }, }),
('m', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 158, y: 82, width: 7, height: 7 }, }),
('#', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 283, y: 68, width: 7, height: 8 }, }),
('5', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 479, y: 74, width: 7, height: 8 }, }),
(',', CharEntry { offset: Vec2i { x: 2, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 479, y: 67, width: 4, height: 4 }, }),
('8', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 407, y: 74, width: 7, height: 8 }, }),
('F', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 22, y: 75, width: 7, height: 8 }, }),
('N', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 283, y: 77, width: 7, height: 8 }, }),
('Q', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 131, y: 77, width: 7, height: 10 }, }),
('Y', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 217, y: 78, width: 7, height: 8 }, }),
(']', CharEntry { offset: Vec2i { x: 1, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 449, y: 77, width: 5, height: 11 }, }),
('2', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 433, y: 72, width: 7, height: 8 }, }),
('9', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 319, y: 74, width: 7, height: 8 }, }),
('&', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 344, y: 70, width: 7, height: 8 }, }),
('>', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 387, y: 75, width: 7, height: 8 }, }),
('O', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 335, y: 77, width: 7, height: 8 }, }),
('P', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 194, y: 77, width: 7, height: 8 }, }),
('S', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 415, y: 78, width: 7, height: 8 }, }),
('T', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 182, y: 78, width: 7, height: 8 }, }),
('3', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 97, y: 74, width: 7, height: 8 }, }),
('c', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 455, y: 80, width: 7, height: 7 }, }),
('l', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 431, y: 81, width: 7, height: 8 }, }),
('p', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 315, y: 83, width: 7, height: 10 }, }),
('0', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 456, y: 71, width: 6, height: 8 }, }),
('s', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 46, y: 83, width: 7, height: 7 }, }),
('Z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 1, y: 78, width: 7, height: 8 }, }),
('"', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 437, y: 68, width: 7, height: 3 }, }),
('^', CharEntry { offset: Vec2i { x: 0, y:7 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 38, y: 79, width: 7, height: 3 }, }),
('u', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 113, y: 83, width: 7, height: 7 }, }),
('v', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 38, y: 83, width: 7, height: 7 }, }),
(':', CharEntry { offset: Vec2i { x: 2, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 86, y: 71, width: 4, height: 7 }, }),
('K', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 327, y: 77, width: 7, height: 8 }, }),
('z', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 208, y: 84, width: 7, height: 7 }, }),
('{', CharEntry { offset: Vec2i { x: 0, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 233, y: 84, width: 6, height: 10 }, }),
('C', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 367, y: 75, width: 7, height: 8 }, }),
('R', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 139, y: 77, width: 7, height: 8 }, }),
('X', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 352, y: 78, width: 7, height: 8 }, }),
('7', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 487, y: 74, width: 7, height: 8 }, }),
('`', CharEntry { offset: Vec2i { x: 1, y:7 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 91, y: 78, width: 5, height: 3 }, }),
('.', CharEntry { offset: Vec2i { x: 2, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 456, y: 68, width: 4, height: 2 }, }),
('b', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 299, y: 79, width: 7, height: 8 }, }),
('}', CharEntry { offset: Vec2i { x: 1, y:-2 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 383, y: 84, width: 6, height: 10 }, }),
('E', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 209, y: 75, width: 7, height: 8 }, }),
('_', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 83, y: 79, width: 7, height: 2 }, }),
('V', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 307, y: 78, width: 7, height: 8 }, }),
('I', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 113, y: 74, width: 5, height: 8 }, }),
('f', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 503, y: 80, width: 7, height: 8 }, }),
('|', CharEntry { offset: Vec2i { x: 2, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 252, y: 76, width: 3, height: 11 }, }),
('h', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 423, y: 81, width: 7, height: 8 }, }),
('L', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 123, y: 77, width: 7, height: 8 }, }),
('t', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 91, y: 83, width: 7, height: 8 }, }),
('o', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 272, y: 83, width: 7, height: 7 }, }),
('!', CharEntry { offset: Vec2i { x: 1, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 209, y: 66, width: 5, height: 8 }, }),
('A', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 174, y: 75, width: 7, height: 8 }, }),
('\\', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 343, y: 79, width: 7, height: 9 }, }),
('/', CharEntry { offset: Vec2i { x: 0, y:-1 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 158, y: 72, width: 7, height: 9 }, }),
('J', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 67, y: 77, width: 7, height: 8 }, }),
('q', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 375, y: 83, width: 7, height: 10 }, }),
('~', CharEntry { offset: Vec2i { x: 0, y:5 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 17, y: 84, width: 7, height: 3 }, }),
('a', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 105, y: 79, width: 7, height: 7 }, }),
('e', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 495, y: 80, width: 7, height: 7 }, }),
('U', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 264, y: 78, width: 7, height: 8 }, }),
('d', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 463, y: 80, width: 7, height: 8 }, }),
('G', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 30, y: 75, width: 7, height: 8 }, }),
('H', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 244, y: 76, width: 7, height: 8 }, }),
('w', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 147, y: 83, width: 7, height: 7 }, }),
('y', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 487, y: 83, width: 7, height: 10 }, }),
('B', CharEntry { offset: Vec2i { x: 0, y:0 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 236, y: 75, width: 7, height: 8 }, }),
('\'', CharEntry { offset: Vec2i { x: 2, y:5 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 275, y: 66, width: 3, height: 3 }, }),
('[', CharEntry { offset: Vec2i { x: 1, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 202, y: 77, width: 5, height: 11 }, }),
('g', CharEntry { offset: Vec2i { x: 0, y:-3 }, advance: Vec2i { x:7, y: 0 }, rect: Recti {x: 9, y: 81, width: 7, height: 10 }, }),
]
 }),
],
format: SourceFormat::Png,
pixels,
    }
}
